apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "livy.fullname" .) .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.nodeport.type }}
  ports:
  - name: http
    nodePort: {{ .Values.service.nodeport.port }}
    port: {{ .Values.service.cluster.port }}
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
