apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "presto.coordinator.fullname" . }}
  labels:
    {{- include "presto.coordinator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "presto.coordinator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "presto.coordinator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "presto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "presto.coordinator.fullname" . }}
        - name: catalog-volume
          secret:
            secretName: {{ template "presto.catalog.fullname" . }}                 
      containers:
        - name: {{ template "presto.coordinator.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.presto.config.http.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info/state
              port: http
          readinessProbe:
            httpGet:
              path: /v1/info/state
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.presto.config.path }}
              name: config-volume      
            - mountPath: {{ .Values.presto.config.path }}/catalog
              name: catalog-volume                  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
