apiVersion: v1
kind: Secret
metadata:
  name: {{ template "presto.catalog.fullname" . }}
  labels:
    {{- include "presto.catalog.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.presto.catalogs | nindent 2 }}
