---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "local-path-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "local-path-provisioner.labels" . | nindent 4 }}  
data:
  config.json: |-
    {
        "nodePathMap":[
        {
            "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths":{{ toJson .Values.config.nodePathMap.DEFAULT_PATH_FOR_NON_LISTED_NODES.paths }}
        }
        ]
    }
