apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "messagebird-sachet.labels" . | nindent 4 }}
  name: {{ template "messagebird-sachet.fullname" . }}
type: Opaque
data:
  access_key: YWRtaW5pc3RyYXRvcg==
  access_key_secret: YWRtaW5pc3RyYXRvcg==
stringData:
  config.yaml: |-
    providers:
      aliyun:
        region_id: cn-hangzhou
        access_key: {{ access_key }}
        access_key_secret: {{ access_key_secret }}
        sign_name: 正泰云
        template_code: SMS_189540900
        template_param_key: code
    receivers:
      - name: "sms"
        provider: "aliyun"
        to:
          - {{ .Labels.to }}