affinity: {}
config:
  nodePathMap:
    DEFAULT_PATH_FOR_NON_LISTED_NODES:
      paths:
      - /opt/local-path-provisioner
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: rancher/local-path-provisioner
  tag: v0.0.12
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
serviceAccount:
  create: true
  name: null
tolerations: []
